---
title: "NFL Wins Pool Update"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: ""
date: ""
output: 
  html_document:
    preserve_yaml: FALSE
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(tidyverse)
library(rvest)
library(formattable)
library(knitr)
library(kableExtra)
library(fuzzyjoin)
library(readxl)
```

```{r read files, echo= FALSE, warning = F}

Draft <- read.csv("DraftResults19.csv", stringsAsFactors = F)
Draft$Team <- factor(Draft$Team, levels = Draft$Team[1:10])
#
# Read NFL Standings
url <- "http://www.espn.com/nfl/standings/_/season/2019/group/league"
webpage <- read_html(url)

teams <- webpage %>% html_nodes(".hide-mobile a") %>% html_text
wins <- webpage %>% html_nodes(".Table__TD:nth-child(1) .stat-cell") %>% html_text %>% as.numeric()
losses <- webpage %>% html_nodes(".Table__TD:nth-child(2) .stat-cell") %>% html_text %>% as.numeric()
ties <- webpage %>% html_nodes(".Table__TD:nth-child(3) .stat-cell") %>% html_text %>% as.numeric()


nfl.standings <- data.frame(Team = teams, W = wins, L = losses, T = ties) %>%
  mutate(GP = rowSums(.[2:4]))

# Determine who each team plays in current week

Schedule_Key <- data.frame(Week = seq(1:17), Date = seq(from = as.Date("2019-09-03"), to = as.Date("2019-12-24"), by = 7))

Current.Week <- Schedule_Key$Week[Schedule_Key$Date == max(Schedule_Key$Date[Schedule_Key$Date <= Sys.Date()])]

Schedule <- read_excel("2019NFLSCHEDULE.xlsx", sheet = "full size (color)", range = "A1:R33")

Schedule_Long <- gather(Schedule, "Week", "Opponent", `1`:`17`)
Schedule_Week <- filter(Schedule_Long, Week == Current.Week) %>% arrange(TEAM)
Schedule_Week$Merge <- sort(as.character(nfl.standings$Team))[c(1:27,29,28,30:32)]
Num.Byes <- sum(Schedule_Week$Opponent == "BYE")/2

# Read 538 Projections
url.2 <- "https://projects.fivethirtyeight.com/2019-nfl-predictions/"
webpage.2 <- read_html(url.2)

teams.538 <- webpage.2 %>% html_nodes(".full") %>% html_text
proj.w <- webpage.2 %>% html_nodes(".num.div") %>% html_text
#Projections <- data.frame(Team = as.character(teams.538), Proj.W = as.numeric(proj.w)) %>%
#  arrange(Team)
Projections <- data.frame(Team = as.character(teams.538)) %>%
  arrange(Team)

Projections$Team <- as.character(Projections$Team)
Projections$Merge <- sort(as.character(nfl.standings$Team))[c(1:20,23:24, 21:22, 25:32)]

# Read ESPN FPI projections
url.4 <- "http://www.espn.com/nfl/story/_/page/Football-Power-Index/espn-nfl-football-power-index"
webpage <- read_html(url.4)

teams.espn <- webpage %>% html_nodes("td:nth-child(1)") %>% html_text
teams.espn <- teams.espn[33:64]

record <- webpage %>% html_nodes("td:nth-child(3)") %>% html_text
record <- record[33:64]
espn.wins <- as.numeric(gsub("-.+$", "", record))

Projections.espn <- data.frame(Team = as.character(teams.espn), Proj.W = espn.wins) %>% arrange(Team)
Projections.espn$Team <- as.character(Projections.espn$Team)
Projections.espn$Merge <- sort(as.character(nfl.standings$Team))[c(1:27,29, 28, 30:32)]

# Read vegas odds
url.3 <- "http://www.vegasinsider.com/nfl/odds/las-vegas/?s=666"
webpage.3 <- read_html(url.3)

odds <- webpage.3 %>% html_nodes(".nowrap:nth-child(3) a") %>% html_text
odds <- gsub("\\n\\t+", "", odds)
odds <- gsub("^.", "", odds)
odds <- gsub("\\n[[:blank:]]+", "", odds)
odds <- gsub("½", ".5", odds)

odds_clean <- data.frame(raw = odds) %>%
  mutate(Game.Num = seq(1:n()),
         Fav = ifelse(substr(raw, 1, 1) %in% c("-", "P"), "Road", "Home"),
         raw = gsub("PK", "-0", raw),
         raw = ifelse(Fav == "Home", gsub("EV", "-0", raw), raw),
         Spread = ifelse(Fav == "Road", as.numeric(gsub("(^.+)[[:space:]].+$", "\\1", raw)), as.numeric(gsub("^[^-]*-[^-]*(-[^ ]*)[[:space:]]-.*$", "\\1", raw))*-1),
         Spread.2 = Spread * -1) %>%
  filter(Game.Num <= 16-Num.Byes) %>%
  gather("Team", "Spread", Spread:Spread.2) %>%
  arrange(Game.Num, Team)

teams.vegas <- webpage.3 %>% html_nodes(".tabletext") %>% html_text

Spreads <- data.frame(Team = teams.vegas[1:(2*(16-Num.Byes))], Spread = odds_clean$Spread) %>%
  mutate(Prob = 1-round(1/(10^((25*Spread)*-1/400)+1),2)) %>%
#  left_join(Projections[,c(1,3)], by = "Team")
  left_join(Projections[,c(1,2)], by = "Team")

Merge.Key <- data.frame(Short = sort(Schedule$TEAM), Long = sort(Projections$Team)[c(1:20,23,24,21,22,25:27,29,28,30:32)], Full = sort(as.character(nfl.standings$Team))[c(1:27,29, 28, 30:32)])

```


## Standings

```{r echo = F, warning=F}
pool.standings <- left_join(Draft[,3:4], nfl.standings, by = c("Selection" = "Team")) %>%
  left_join(Projections.espn[,2:3], by = c("Selection" = "Merge")) %>%
  arrange(Selection) %>%
  group_by(Team) %>%
  summarise_at(vars(-Selection), funs(sum)) %>%
  mutate(Rank = rank(-W, ties.method = "min"),
         Games.Left = 48 - GP,
         W.Pct = percent(W/GP, digits = 1),
         W.Pct.Rk = rank(-W.Pct, ties.method = "min"),
         Proj.Rank = rank(-Proj.W, ties.method = "min")) %>%
  arrange(Rank) %>%
  select(Rank, Team, W, Games.Left, W.Pct, W.Pct.Rk, Proj.W, Proj.Rank) %>%
#  select(Rank, Team, W, Games.Left, W.Pct) %>%
  rename(Wins = W) 

pool.standings %>%
  kable(col.names = c("Rank", "Team", "Wins", "Remaining Games", "Win %", "Win % Rank", "Projected Wins", "Projected Rank"), align = "c") %>%
#  kable(col.names = c("Rank", "Team", "Wins", "Remaining Games", "Win %"), align = "c") %>%
  kable_styling(bootstrap_options = c("hover","condensed", "responsive"), full_width = F)


  

```

* Projected wins taken from [ESPN FPI projections](http://www.espn.com/nfl/story/_/page/Football-Power-Index/espn-nfl-football-power-index)

## Expanded Standings

```{r echo = F, warning = F}

expanded.standings <- left_join(nfl.standings[, 1:2], Draft[, 3:4], by = c("Team" = "Selection")) %>%
  rename(Picker = Team.y) %>%
  mutate(Picker = as.character(Picker)) %>%
  filter(!is.na(Picker)) %>%
  left_join(Spreads[, 3:4], by = c("Team" = "Merge")) %>%
  left_join(Schedule_Week[, 3:4], by = c("Team" = "Merge")) %>%
  left_join(pool.standings[, 2:3], by = c("Picker" = "Team")) %>%
  left_join(Projections.espn[,2:3], by = c("Team" = "Merge")) %>%
  arrange(desc(Wins), Picker, desc(W), Team)

Pool.Order <- unique(expanded.standings$Picker)

names_broken <- c("Team", "Wins","Projected<br/>Wins" ,"Next<br/>Opponent", "Win Probability<br/>in Next Game")

expanded.standings %>%
  select(Team, W, Proj.W, Opponent, Prob) %>%
  kable(col.names = names_broken, escape = F) %>%
  kable_styling(bootstrap_options = c("hover"), full_width = F, position = "left") %>%
  group_rows(Pool.Order[1], 1,3) %>%
  group_rows(Pool.Order[2], 4,6) %>%
  group_rows(Pool.Order[3], 7,9) %>%
  group_rows(Pool.Order[4], 10,12) %>%
  group_rows(Pool.Order[5], 13,15) %>%
  group_rows(Pool.Order[6], 16,18) %>%
  group_rows(Pool.Order[7], 19,21) %>%
  group_rows(Pool.Order[8], 22,24) %>%
  group_rows(Pool.Order[9], 25,27) %>%
  group_rows(Pool.Order[10], 28,30) 

#%>%
#  scroll_box(width = "100%", height = "200px")
```

* Win probability calculated from [consensus vegas point spreads](http://www.vegasinsider.com/nfl/odds/las-vegas/?s=666)

## Weekly Head-to-Heads

```{r H2H, echo = F, warning=F}
First_Place <- max(pool.standings$Wins)
Third_Place <- pool.standings$Wins[3]

# fix road team for london game
Schedule_Long$Opponent[Schedule_Long$TEAM == "CAR" & Schedule_Long$Week == 6] <- "@TB"

Matchups <- Schedule_Long %>%
  filter(Week == Current.Week,
         grepl("@", Opponent)) %>%
  select(-Week) %>%
  mutate(Opponent = gsub("@", "", Opponent),
         Game = seq(1:n())) %>%
  rename(Home = TEAM,
         Away = Opponent) %>%
  gather("Location", "Team", Home:Away) %>%
  left_join(Merge.Key[,c(1,3)], by = c("Team" = "Short")) %>%
  left_join(Draft[,c(3,4)] %>% rename("Person" = "Team"), by = c("Full" = "Selection")) %>%
  left_join(pool.standings[, c(2:3)] %>% rename("Person" = "Team"), by ="Person") %>%
  left_join(Spreads[, c(3,4)], by = c("Full" = "Merge")) %>%
  select(-Full) %>%
  unite("temp", Team,Person,Wins,Prob, sep = "-") %>%
  spread(Location, temp) %>%
  separate(Home, c("Home", "Home_Person", "Home_Wins", "Home_Prob"), sep = "-") %>%
  separate(Away, c("Away", "Away_Person", "Away_Wins", "Away_Prob"), sep = "-") %>%
  mutate_at(vars(Home_Wins, Home_Prob, Away_Wins, Away_Prob), funs(as.numeric(.))) %>%
  mutate_at(vars(Home_Wins, Away_Wins), funs(ifelse(is.na(.), min(pool.standings$Wins), .))) %>%
  rowwise() %>%
  mutate(Rank.Rating_First = (First_Place - Home_Wins) + (First_Place - Away_Wins),
         Rank.Rating_Money = (max(0, Third_Place - Home_Wins, na.rm = T) + max(0, Third_Place - Away_Wins, na.rm = T)),
         Prob.Rating = max(Home_Prob, Away_Prob)) %>%
  ungroup() %>%
  arrange(Rank.Rating_First, Rank.Rating_Money, Prob.Rating) %>%
  mutate(Leverage.Score = 1:n(),
         Output = paste0("(", Away_Person,") ", Away, " @ ", Home, " (", Home_Person,")"),
         At = "@") %>%
  select(Home_Person, Home, At, Away, Away_Person, Leverage.Score) %>%
  mutate_at(vars(Away_Person, Home_Person), funs(ifelse(. == "NA", "", .)))

colfunc <- colorRampPalette(c("red", "white"))

Matchups %>%
  mutate(
    Indicator.Cell = "ReallyLongName",
    Indicator.Cell = cell_spec(
    Indicator.Cell, color = colfunc(16-Num.Byes), 
    background = colfunc(16-Num.Byes)
  )) %>%
  select(-Leverage.Score) %>%
    kable(col.names = c("Person", "Team", "", "Team", "Person", "Leverage"), escape = F) %>%
  kable_styling(bootstrap_options = c("hover"), full_width = F, position = "left")
  
```

Leverage measured by:  
* Combined number of wins from first place  
* Combined number of wins from the money (third place)  
* The game with the shortest spread

## Draft Analysis

```{r echo = F, warning = F}
full.standings <- left_join(nfl.standings[, 1:2], Draft[, 2:4], by = c("Team" = "Selection")) %>%
  rename(Picker = Team.y) %>%
  mutate(Picker = as.character(Picker))

full.standings$Pick[is.na(full.standings$Pick)] <- c(31,32)
full.standings$Picker[is.na(full.standings$Picker)] <- "Not Picked"

pool.rosters <- left_join(Draft, nfl.standings, by = c("Selection" = "Team")) %>%
  mutate(Exp.W = nfl.standings$W[Pick],
         PvE = W - Exp.W) %>%
  group_by(Team) %>%
  mutate(Total = sum(W)) %>%
  rowwise() %>%
  mutate(better.pick = sum(full.standings$Pick[full.standings$Picker != Team] > Pick & full.standings$W[full.standings$Picker != Team] > W)) %>%
  arrange(desc(Total), Team, Pick)


names_broken <- c("Team", "Wins", "Draft<br/>Spot", "Expected<br/>Wins", "Performance vs.<br/>Expectation", "Better<br/>Choices")

pool.rosters %>%
  select(Selection, W, Pick, Exp.W, PvE, better.pick) %>%
  kable(col.names = names_broken, escape = F) %>%
  kable_styling(bootstrap_options = c("hover"), full_width = F, position = "left") %>%
  group_rows(pool.standings$Team[1], 1,3) %>%
  group_rows(pool.standings$Team[2], 4,6) %>%
  group_rows(pool.standings$Team[3], 7,9) %>%
  group_rows(pool.standings$Team[4], 10,12) %>%
  group_rows(pool.standings$Team[5], 13,15) %>%
  group_rows(pool.standings$Team[6], 16,18) %>%
  group_rows(pool.standings$Team[7], 19,21) %>%
  group_rows(pool.standings$Team[8], 22,24) %>%
  group_rows(pool.standings$Team[9], 25,27) %>%
  group_rows(pool.standings$Team[10], 28,30)



```



## Draft Results

```{r draft, echo=FALSE}
graph_data <- full.standings %>%
  select(Picker, Team, W, Pick)

graph_data$Picker <- factor(graph_data$Picker, levels = c(as.character(Draft$Team[1:10]), "Not Picked"))

ggplot(graph_data, aes(x = Picker, y = Pick)) + 
  geom_point() +
  geom_text(aes(label = Team, color = W), size = 3, hjust = 0, nudge_x = 0.15) + 
  scale_y_reverse(name = "Overall Selection", breaks = c(1,10,20,30)) +
  scale_color_gradient(name = "Wins", low = "red", high = "darkblue")+
  coord_cartesian(xlim = c(0.75,14)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


